language: php

php:
  - 5.3

env:
  - SYMFONY_VERSION="2.2.*"

before_script:
  - wget http://getcomposer.org/composer.phar
  - composer require symfony/framework-bundle:${SYMFONY_VERSION}
  - php composer.phar install --dev

script: phpunit