language: php

php:
  - 5.3

env:
  - SYMFONY_VERSION="2.2.*"

before_script:
  - wget http://getcomposer.org/composer.phar
  - composer require symfony/framework-bundle:v2.2.0-RC2
  - php composer.phar install --dev

script: phpunit